// Mandado: Inicio → Mandados → Mandado → completar → resumen (sin enviar).
const { startRecording } = await import('file:///C:/Users/PC/Desktop/GoDelivery/reel/recorder.mjs');
const r = await startRecording(ctx, page, 'mandado');
await page.waitForTimeout(1200);
await r.tap(page.locator('#home-mandados-btn'), { pause: 1700 });
r.mark('menu');
await r.tap(page.getByText('Compramos lo que necesites').first(), { pause: 1500 });
r.mark('form');
const stop = page.getByPlaceholder(/Verduler/);
await r.tap(stop, { pause: 300 });
r.mark('type1');
await r.type(stop, 'Farmacia');
r.mark('type1-end');
await page.waitForTimeout(400);
const items = page.getByPlaceholder(/1kg papas/);
await r.tap(items, { pause: 300 });
r.mark('type2');
await r.type(items, 'Ibuprofeno y alcohol en gel');
r.mark('type2-end');
await page.waitForTimeout(500);
await r.tap(page.getByText(/Elegir destino/).first(), { pause: 1400 });
r.mark('destino');
await r.tap([200, 465], { pause: 1300 });
const det = page.getByPlaceholder(/Detalle: Nro/);
await r.tap(det, { pause: 300 });
r.mark('type3');
await r.type(det, 'Timbre 2');
r.mark('type3-end');
await page.waitForTimeout(500);
await r.tap(page.getByText('SIGUIENTE').last(), { pause: 1500 });
r.mark('resumen');
await r.tap(page.getByText('Efectivo', { exact: true }).last(), { pause: 1200 });
const meta = await r.stop();
await page.screenshot({ path: 'captures/mandado-end.png', scale: 'css' });
return { frames: meta.frames.length, secs: meta.frames.at(-1).t, marks: meta.marks.map(m => m.label + '@' + m.t.toFixed(1)) };
